
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  app:
    image: springboot-demo-app
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_ACTIVE_PROFILE}
      ADMIN_USER_NAME: ${ADMIN_USER_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_ROLE: ${ADMIN_ROLE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
