# Development profile settings

# Hibernate ddl-auto: create-drop, update (dangerous for prod)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (only in dev)
spring.jpa.show-sql=true

# Enable pretty print if needed
spring.jpa.properties.hibernate.format_sql=true
