# Application name
spring.application.name=springboot-demo

# Default profile
spring.profiles.active=${SPRING_ACTIVE_PROFILE:dev}

# ---------- Common Database Settings ----------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db:${POSTGRES_PORT:5432}/${POSTGRES_DB:demo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# ---------- Common JPA/Hibernate Settings ----------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---------- Security Settings ----------
spring.security.user.name=${SPRING_SECURITY_USER_NAME:user}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}
