spring.application.name=springboot-demo

# Spring security login credentials
spring.security.user.name=${SPRING_SECURITY_USER_NAME:user}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}


# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://db:${POSTGRES_PORT:5432}/${POSTGRES_DB:demo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
